### ISSUE TITLE
rss subscribe has nothing

### ISSUE THREAD

**Issue by ghost** [TheLucasMoore/consensual_software#28]
At the bottom of the [homepage](http://consensualsoftware.com/), the Subscribe button leads to an empty feed, which does not provide any new information for the user.

http://consensualsoftware.com/feed.xml

I suggest you delete subscribe button.

I've sent a PR for this issue.
https://github.com/TheLucasMoore/consensual_software/pull/27

**Comment by dmleong** [comment]
Merged PR, thanks for doing this!
