### ISSUE TITLE
What is consent? 

### ISSUE THREAD

**Issue by dmleong** [TheLucasMoore/consensual_software#3]
What is the definition of consent that we want to use for the site? There are a lot of resources out there that mainly deal with sexual contact, but what are we trying to say here?

**Comment by TheLucasMoore** [comment]
Consent is explicit, enthusiastic confirmation in support of any action, from all parties involved. Consensual communication is a mix of transparency and honesty. As it relates to the design of software, a simple example is app permissions. When opening an app for the first time, users are prompted with a choice of whether to allow the app to access their photos, contacts or location. 

This process as it now exists is not perfect, however. There is some granularity about whether an app can see your location never, always, or only while using the application. Users do not have the entire context around what their geolocation data might be used for, for example. Applications should be designed to more specifically mention how your data will be stored, whether it will be bought or sold.

What else? Any more examples you can think of?

**Comment by dmleong** [comment]
I think that we should be also discuss that consent requires clear communication about what kind of permissions are being used by a site or service. Hiding permissions under a link is not clear and violates consent through coercion.

**Comment by dmleong** [comment]
Oh whoops, didn't see that this is the definition of consent, not consensual software. 

I think we should make sure there's a clear distinction here between what is colloquially understood as consent (particularly since most folks assume it has to be related to sex) and what we're trying to get at here. 

- Consent is explicit, enthusiastic confirmation in support of any action, from all parties involved. 
- Consent cannot be coerced, manipulated, bought, sold, or forced upon anyone. 

> Consensual communication is a mix of transparency and honesty.

I like keeping the focus on transparency and honesty, but I'm not a terribly big fan of the phrase "consensual communication". To me, building consensual software certainly relies on clear and transparent communication from companies to their end users, but "consensual communication" seems like it's a separate definition that could be confusing. 

If I were to structure this as a blog post, I would: 

1) define explicit consent
2) define implicit/implied consent 
3) define consensual software as it relates to explicit consent 
4) give examples of non-consensual practices through implied/implicit consent

**Comment by TheLucasMoore** [comment]
That's a great outline.

**Comment by dmleong** [comment]
Shipped via #12
