### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by dmleong** [TheLucasMoore/consensual_software#4]
Put your bios here

And faces. Circles not required ⚪️

**Comment by dmleong** [comment]
Danielle Leong is an engineer on GitHub’s Community & Safety team who focuses on building consensual software and tools that help make online platforms safer, more welcoming, and inclusive. She is also the founder of Feerless, an app that provides trigger warnings for Netflix users with PTSD. She’s passionate about online privacy, inclusivity in tech, mental health awareness, and improving online good citizenship. In her spare time, she takes mediocre photos of her dog on Instagram, dresses up as a dinosaur, and eats lots of pizza - occasionally all at the same time. 

![headshot-pizza](https://user-images.githubusercontent.com/2171822/30089335-ee99c3b4-9260-11e7-83e1-911fee852a43.jpg)

**Comment by TheLucasMoore** [comment]
Lucas believes wholeheartedly in building and sharing an understanding of healthy consent structures, whether in software design, advertising or in relationships. He knows this to be especially important to teach young boys. He's worn many hats, from working in advertising, to teaching bilingual elementary school with Teach for America. He now works as a software engineer in Denver, CO.

![lucas](https://user-images.githubusercontent.com/10284147/30525184-502988d2-9bbf-11e7-90ef-4ed426312d78.JPG)

**Comment by dmleong** [comment]
lol I never noticed the 🐝 ! 

Maybe we should crop that photo a tad though 😉

**Comment by TheLucasMoore** [comment]
Lucas believes wholeheartedly in building and sharing an understanding of healthy consent structures, whether in software design, advertising or in relationships. He knows this to be especially important to teach young boys. He's worn many hats, from working in advertising, to teaching bilingual elementary school with Teach for America. He now works as a software engineer in Denver, CO.

![lucas2](https://user-images.githubusercontent.com/10284147/30624811-b4210fd6-9d7c-11e7-9088-27fdf7a3695a.jpg)

**Comment by dmleong** [comment]
Added this, but need to update headshots. Closing for now
